/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_blank_line_token1 = 1,
  sym_section_delimiter = 2,
  sym_section_heading = 3,
  sym_subsection_heading = 4,
  anon_sym_COLON = 5,
  aux_sym_key_value_pair_token1 = 6,
  sym_plain_key = 7,
  sym_hash_key = 8,
  anon_sym_DQUOTE = 9,
  anon_sym_SQUOTE = 10,
  sym_double_string_content = 11,
  sym_single_string_content = 12,
  anon_sym_LBRACK = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACK = 15,
  sym_number = 16,
  sym_boolean = 17,
  sym_null_value = 18,
  sym_unquoted_string = 19,
  sym_block_scalar_indicator = 20,
  sym_attestation_start = 21,
  sym_attestation_content = 22,
  sym_attestation_end = 23,
  anon_sym_DASH = 24,
  sym_comment = 25,
  sym_document = 26,
  sym__toplevel = 27,
  sym_blank_line = 28,
  sym_key_value_pair = 29,
  sym_key = 30,
  sym_value = 31,
  sym_quoted_string = 32,
  sym_array = 33,
  sym_attestation_block = 34,
  sym_list_item = 35,
  aux_sym_document_repeat1 = 36,
  aux_sym_array_repeat1 = 37,
  aux_sym_attestation_block_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_blank_line_token1] = "blank_line_token1",
  [sym_section_delimiter] = "section_delimiter",
  [sym_section_heading] = "section_heading",
  [sym_subsection_heading] = "subsection_heading",
  [anon_sym_COLON] = ":",
  [aux_sym_key_value_pair_token1] = "key_value_pair_token1",
  [sym_plain_key] = "plain_key",
  [sym_hash_key] = "hash_key",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym_double_string_content] = "double_string_content",
  [sym_single_string_content] = "single_string_content",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_null_value] = "null_value",
  [sym_unquoted_string] = "unquoted_string",
  [sym_block_scalar_indicator] = "block_scalar_indicator",
  [sym_attestation_start] = "attestation_start",
  [sym_attestation_content] = "attestation_content",
  [sym_attestation_end] = "attestation_end",
  [anon_sym_DASH] = "- ",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__toplevel] = "_toplevel",
  [sym_blank_line] = "blank_line",
  [sym_key_value_pair] = "key_value_pair",
  [sym_key] = "key",
  [sym_value] = "value",
  [sym_quoted_string] = "quoted_string",
  [sym_array] = "array",
  [sym_attestation_block] = "attestation_block",
  [sym_list_item] = "list_item",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_attestation_block_repeat1] = "attestation_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_blank_line_token1] = aux_sym_blank_line_token1,
  [sym_section_delimiter] = sym_section_delimiter,
  [sym_section_heading] = sym_section_heading,
  [sym_subsection_heading] = sym_subsection_heading,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_key_value_pair_token1] = aux_sym_key_value_pair_token1,
  [sym_plain_key] = sym_plain_key,
  [sym_hash_key] = sym_hash_key,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_double_string_content] = sym_double_string_content,
  [sym_single_string_content] = sym_single_string_content,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_null_value] = sym_null_value,
  [sym_unquoted_string] = sym_unquoted_string,
  [sym_block_scalar_indicator] = sym_block_scalar_indicator,
  [sym_attestation_start] = sym_attestation_start,
  [sym_attestation_content] = sym_attestation_content,
  [sym_attestation_end] = sym_attestation_end,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__toplevel] = sym__toplevel,
  [sym_blank_line] = sym_blank_line,
  [sym_key_value_pair] = sym_key_value_pair,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [sym_quoted_string] = sym_quoted_string,
  [sym_array] = sym_array,
  [sym_attestation_block] = sym_attestation_block,
  [sym_list_item] = sym_list_item,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_attestation_block_repeat1] = aux_sym_attestation_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_blank_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_section_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_section_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_subsection_heading] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_key_value_pair_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_plain_key] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_double_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_single_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_null_value] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_block_scalar_indicator] = {
    .visible = true,
    .named = true,
  },
  [sym_attestation_start] = {
    .visible = true,
    .named = true,
  },
  [sym_attestation_content] = {
    .visible = true,
    .named = true,
  },
  [sym_attestation_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_attestation_block] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attestation_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '\n', 42,
        '"', 69,
        '#', 18,
        '\'', 71,
        ',', 79,
        '-', 20,
        ':', 46,
        '@', 32,
        '[', 77,
        ']', 80,
        'f', 48,
        'n', 64,
        't', 58,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(87);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '-') ADVANCE(100);
      if (lookahead == '[') ADVANCE(77);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(65);
      if (lookahead == 't') ADVANCE(59);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']') ADVANCE(102);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(88);
      if (lookahead == ' ') SKIP(2);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '-') ADVANCE(100);
      if (lookahead == '[') ADVANCE(77);
      if (lookahead == ']') ADVANCE(80);
      if (lookahead == 'f') ADVANCE(90);
      if (lookahead == 'n') ADVANCE(98);
      if (lookahead == 't') ADVANCE(95);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(102);
      END_STATE();
    case 3:
      if (lookahead == '\t') ADVANCE(89);
      if (lookahead == ' ') SKIP(3);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '-') ADVANCE(100);
      if (lookahead == '[') ADVANCE(77);
      if (lookahead == 'f') ADVANCE(90);
      if (lookahead == 'n') ADVANCE(98);
      if (lookahead == 't') ADVANCE(95);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']') ADVANCE(102);
      END_STATE();
    case 4:
      if (lookahead == '\t') SKIP(4);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(43);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == ']') ADVANCE(11);
      if (('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(44);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(104);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == '@') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == 'd') ADVANCE(107);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == '\n') ADVANCE(105);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(110);
      if (lookahead == '#') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 19:
      if (lookahead == ' ') ADVANCE(108);
      if (lookahead == '-') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == ' ') ADVANCE(108);
      if (lookahead == '-') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 21:
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '[') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '[') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '[') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '[') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '[') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 27:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 28:
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == ']') ADVANCE(10);
      if (('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(30);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(107);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 35:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(30);
      END_STATE();
    case 36:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 37:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 38:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 39:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_section_delimiter);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_section_heading);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_subsection_heading);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_key_value_pair_token1);
      if (lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'a') ADVANCE(52);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'a') ADVANCE(55);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'e') ADVANCE(85);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'e') ADVANCE(85);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(60);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(86);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(86);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(61);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(53);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(54);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'r') ADVANCE(62);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'r') ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 's') ADVANCE(50);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 's') ADVANCE(51);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'u') ADVANCE(50);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'u') ADVANCE(51);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'u') ADVANCE(56);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'u') ADVANCE(57);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_plain_key);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_plain_key);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_hash_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_double_string_content);
      if (lookahead == '\\') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_double_string_content);
      if (lookahead == '\\') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_single_string_content);
      if (lookahead == '\\') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_single_string_content);
      if (lookahead == '\\') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_null_value);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_unquoted_string);
      ADVANCE_MAP(
        '\t', 87,
        ' ', 87,
        '"', 70,
        '#', 101,
        '\'', 72,
        '-', 100,
        '[', 78,
        'f', 49,
        'n', 65,
        't', 59,
        '>', 103,
        '|', 103,
        ',', 102,
        ':', 102,
        ']', 102,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_unquoted_string);
      ADVANCE_MAP(
        '\t', 88,
        ' ', 88,
        '"', 70,
        '\'', 72,
        '-', 100,
        '[', 78,
        ']', 81,
        'f', 90,
        'n', 98,
        't', 95,
        '>', 103,
        '|', 103,
        '#', 102,
        ',', 102,
        ':', 102,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_unquoted_string);
      ADVANCE_MAP(
        '\t', 89,
        ' ', 89,
        '"', 70,
        '\'', 72,
        '-', 100,
        '[', 78,
        'f', 90,
        'n', 98,
        't', 95,
        '>', 103,
        '|', 103,
        '#', 102,
        ',', 102,
        ':', 102,
        ']', 102,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'a') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'e') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'l') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'l') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'l') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'r') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 's') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'u') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'u') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_block_scalar_indicator);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_attestation_start);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_attestation_content);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_attestation_end);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_attestation_end);
      if (lookahead == '\n') ADVANCE(106);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 40},
  [3] = {.lex_state = 40},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 40},
  [12] = {.lex_state = 40},
  [13] = {.lex_state = 40},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 40},
  [17] = {.lex_state = 40},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 29},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 75},
  [36] = {.lex_state = 73},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_blank_line_token1] = ACTIONS(1),
    [sym_section_delimiter] = ACTIONS(1),
    [sym_section_heading] = ACTIONS(1),
    [sym_subsection_heading] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_plain_key] = ACTIONS(1),
    [sym_hash_key] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_null_value] = ACTIONS(1),
    [sym_block_scalar_indicator] = ACTIONS(1),
    [sym_attestation_end] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(40),
    [sym__toplevel] = STATE(2),
    [sym_blank_line] = STATE(2),
    [sym_key_value_pair] = STATE(2),
    [sym_key] = STATE(43),
    [sym_attestation_block] = STATE(2),
    [sym_list_item] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_blank_line_token1] = ACTIONS(5),
    [sym_section_delimiter] = ACTIONS(7),
    [sym_section_heading] = ACTIONS(7),
    [sym_subsection_heading] = ACTIONS(9),
    [sym_plain_key] = ACTIONS(11),
    [sym_hash_key] = ACTIONS(11),
    [sym_attestation_start] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_comment] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      aux_sym_blank_line_token1,
    ACTIONS(13), 1,
      sym_attestation_start,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_subsection_heading,
    STATE(43), 1,
      sym_key,
    ACTIONS(11), 2,
      sym_plain_key,
      sym_hash_key,
    ACTIONS(19), 3,
      sym_section_delimiter,
      sym_section_heading,
      sym_comment,
    STATE(3), 6,
      sym__toplevel,
      sym_blank_line,
      sym_key_value_pair,
      sym_attestation_block,
      sym_list_item,
      aux_sym_document_repeat1,
  [36] = 9,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      aux_sym_blank_line_token1,
    ACTIONS(31), 1,
      sym_subsection_heading,
    ACTIONS(37), 1,
      sym_attestation_start,
    ACTIONS(40), 1,
      anon_sym_DASH,
    STATE(43), 1,
      sym_key,
    ACTIONS(34), 2,
      sym_plain_key,
      sym_hash_key,
    ACTIONS(28), 3,
      sym_section_delimiter,
      sym_section_heading,
      sym_comment,
    STATE(3), 6,
      sym__toplevel,
      sym_blank_line,
      sym_key_value_pair,
      sym_attestation_block,
      sym_list_item,
      aux_sym_document_repeat1,
  [72] = 8,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    STATE(38), 1,
      sym_key,
    STATE(45), 1,
      sym_value,
    ACTIONS(43), 2,
      sym_plain_key,
      sym_hash_key,
    STATE(23), 2,
      sym_quoted_string,
      sym_array,
    ACTIONS(51), 5,
      sym_number,
      sym_boolean,
      sym_null_value,
      sym_unquoted_string,
      sym_block_scalar_indicator,
  [103] = 7,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    STATE(25), 1,
      sym_value,
    STATE(23), 2,
      sym_quoted_string,
      sym_array,
    ACTIONS(51), 5,
      sym_number,
      sym_boolean,
      sym_null_value,
      sym_unquoted_string,
      sym_block_scalar_indicator,
  [130] = 7,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_value,
    STATE(23), 2,
      sym_quoted_string,
      sym_array,
    ACTIONS(51), 5,
      sym_number,
      sym_boolean,
      sym_null_value,
      sym_unquoted_string,
      sym_block_scalar_indicator,
  [157] = 7,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      sym_value,
    STATE(23), 2,
      sym_quoted_string,
      sym_array,
    ACTIONS(51), 5,
      sym_number,
      sym_boolean,
      sym_null_value,
      sym_unquoted_string,
      sym_block_scalar_indicator,
  [184] = 6,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    STATE(44), 1,
      sym_value,
    STATE(23), 2,
      sym_quoted_string,
      sym_array,
    ACTIONS(51), 5,
      sym_number,
      sym_boolean,
      sym_null_value,
      sym_unquoted_string,
      sym_block_scalar_indicator,
  [208] = 6,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    STATE(41), 1,
      sym_value,
    STATE(23), 2,
      sym_quoted_string,
      sym_array,
    ACTIONS(51), 5,
      sym_number,
      sym_boolean,
      sym_null_value,
      sym_unquoted_string,
      sym_block_scalar_indicator,
  [232] = 6,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    STATE(34), 1,
      sym_value,
    STATE(23), 2,
      sym_quoted_string,
      sym_array,
    ACTIONS(51), 5,
      sym_number,
      sym_boolean,
      sym_null_value,
      sym_unquoted_string,
      sym_block_scalar_indicator,
  [256] = 2,
    ACTIONS(61), 1,
      sym_subsection_heading,
    ACTIONS(59), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [271] = 2,
    ACTIONS(65), 1,
      sym_subsection_heading,
    ACTIONS(63), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [286] = 2,
    ACTIONS(69), 1,
      sym_subsection_heading,
    ACTIONS(67), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [301] = 2,
    ACTIONS(73), 1,
      sym_subsection_heading,
    ACTIONS(71), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [316] = 2,
    ACTIONS(77), 1,
      sym_subsection_heading,
    ACTIONS(75), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [331] = 2,
    ACTIONS(81), 1,
      sym_subsection_heading,
    ACTIONS(79), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [346] = 2,
    ACTIONS(85), 1,
      sym_subsection_heading,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [361] = 2,
    ACTIONS(89), 1,
      sym_subsection_heading,
    ACTIONS(87), 9,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      sym_section_delimiter,
      sym_section_heading,
      sym_plain_key,
      sym_hash_key,
      sym_attestation_start,
      anon_sym_DASH,
      sym_comment,
  [376] = 1,
    ACTIONS(91), 3,
      aux_sym_blank_line_token1,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [382] = 3,
    ACTIONS(93), 1,
      sym_attestation_content,
    ACTIONS(95), 1,
      sym_attestation_end,
    STATE(31), 1,
      aux_sym_attestation_block_repeat1,
  [392] = 1,
    ACTIONS(97), 3,
      aux_sym_blank_line_token1,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [398] = 3,
    ACTIONS(99), 1,
      sym_attestation_content,
    ACTIONS(101), 1,
      sym_attestation_end,
    STATE(20), 1,
      aux_sym_attestation_block_repeat1,
  [408] = 1,
    ACTIONS(103), 3,
      aux_sym_blank_line_token1,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [414] = 1,
    ACTIONS(105), 3,
      aux_sym_blank_line_token1,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [420] = 3,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    STATE(28), 1,
      aux_sym_array_repeat1,
  [430] = 1,
    ACTIONS(111), 3,
      aux_sym_blank_line_token1,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [436] = 1,
    ACTIONS(113), 3,
      aux_sym_blank_line_token1,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [442] = 3,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      aux_sym_array_repeat1,
  [452] = 1,
    ACTIONS(119), 3,
      aux_sym_blank_line_token1,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [458] = 3,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      aux_sym_array_repeat1,
  [468] = 3,
    ACTIONS(126), 1,
      sym_attestation_content,
    ACTIONS(129), 1,
      sym_attestation_end,
    STATE(31), 1,
      aux_sym_attestation_block_repeat1,
  [478] = 2,
    ACTIONS(131), 1,
      aux_sym_blank_line_token1,
    ACTIONS(133), 1,
      aux_sym_key_value_pair_token1,
  [485] = 2,
    ACTIONS(135), 1,
      aux_sym_blank_line_token1,
    ACTIONS(137), 1,
      aux_sym_key_value_pair_token1,
  [492] = 1,
    ACTIONS(124), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [497] = 2,
    ACTIONS(139), 1,
      anon_sym_SQUOTE,
    ACTIONS(141), 1,
      sym_single_string_content,
  [504] = 2,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      sym_double_string_content,
  [511] = 1,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
  [515] = 1,
    ACTIONS(147), 1,
      anon_sym_COLON,
  [519] = 1,
    ACTIONS(145), 1,
      anon_sym_SQUOTE,
  [523] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
  [527] = 1,
    ACTIONS(151), 1,
      aux_sym_blank_line_token1,
  [531] = 1,
    ACTIONS(153), 1,
      anon_sym_COLON,
  [535] = 1,
    ACTIONS(155), 1,
      anon_sym_COLON,
  [539] = 1,
    ACTIONS(157), 1,
      aux_sym_blank_line_token1,
  [543] = 1,
    ACTIONS(159), 1,
      aux_sym_blank_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 103,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 157,
  [SMALL_STATE(8)] = 184,
  [SMALL_STATE(9)] = 208,
  [SMALL_STATE(10)] = 232,
  [SMALL_STATE(11)] = 256,
  [SMALL_STATE(12)] = 271,
  [SMALL_STATE(13)] = 286,
  [SMALL_STATE(14)] = 301,
  [SMALL_STATE(15)] = 316,
  [SMALL_STATE(16)] = 331,
  [SMALL_STATE(17)] = 346,
  [SMALL_STATE(18)] = 361,
  [SMALL_STATE(19)] = 376,
  [SMALL_STATE(20)] = 382,
  [SMALL_STATE(21)] = 392,
  [SMALL_STATE(22)] = 398,
  [SMALL_STATE(23)] = 408,
  [SMALL_STATE(24)] = 414,
  [SMALL_STATE(25)] = 420,
  [SMALL_STATE(26)] = 430,
  [SMALL_STATE(27)] = 436,
  [SMALL_STATE(28)] = 442,
  [SMALL_STATE(29)] = 452,
  [SMALL_STATE(30)] = 458,
  [SMALL_STATE(31)] = 468,
  [SMALL_STATE(32)] = 478,
  [SMALL_STATE(33)] = 485,
  [SMALL_STATE(34)] = 492,
  [SMALL_STATE(35)] = 497,
  [SMALL_STATE(36)] = 504,
  [SMALL_STATE(37)] = 511,
  [SMALL_STATE(38)] = 515,
  [SMALL_STATE(39)] = 519,
  [SMALL_STATE(40)] = 523,
  [SMALL_STATE(41)] = 527,
  [SMALL_STATE(42)] = 531,
  [SMALL_STATE(43)] = 535,
  [SMALL_STATE(44)] = 539,
  [SMALL_STATE(45)] = 543,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 6, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 6, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_pair, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value_pair, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attestation_block, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attestation_block, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attestation_block, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attestation_block, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_pair, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_value_pair, 5, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attestation_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attestation_block_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [149] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_a2ml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "a2ml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
